version: 2.1

jobs:
  build:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Docker hub login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build image
          command: docker build -t senasi/cron:${CIRCLE_TAG} .
      - run:
          name: Push image
          command: docker push senasi/cron:${CIRCLE_TAG}
      - run:
          name: Push major tag image
          command: |
            MAJOR_TAG=`echo "${CIRCLE_TAG}" | sed -nre 's/^[^0-9]*(([0-9]+\.)?[0-9]+).*/\1/p'`
            docker tag senasi/cron:${CIRCLE_TAG} senasi/cron:${MAJOR_TAG}
            docker push senasi/cron:${MAJOR_TAG}
      - run:
          name: Push latest
          command: |
            docker tag senasi/cron:${CIRCLE_TAG} senasi/cron:latest
            docker push senasi/cron:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
