version: 2.1

commands:
  build_and_push_docker_image:
    parameters:
      tag:
        type: string
    steps:
      - run:
          name: Build image
          command: docker build -t senasi/cron:<< parameters.tag >> .
      - run:
          name: Push image
          command: docker push senasi/cron:<< parameters.tag >>
      - run:
          name: Push latest
          command: docker tag senasi/cron:<< parameters.tag >> senasi/cron:latest && docker push senasi/cron:latest
         
jobs:
  build:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Docker hub login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - build_and_push_docker_image:
          tag: ${CIRCLE_TAG}

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
